/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry.tables.daos;


import com.okeicalm.simpleJournalEntry.tables.Balls;
import com.okeicalm.simpleJournalEntry.tables.records.BallsRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class BallsDao extends DAOImpl<BallsRecord, com.okeicalm.simpleJournalEntry.tables.pojos.Balls, Long> {

    /**
     * Create a new BallsDao without any configuration
     */
    public BallsDao() {
        super(Balls.BALLS, com.okeicalm.simpleJournalEntry.tables.pojos.Balls.class);
    }

    /**
     * Create a new BallsDao with an attached configuration
     */
    @Autowired
    public BallsDao(Configuration configuration) {
        super(Balls.BALLS, com.okeicalm.simpleJournalEntry.tables.pojos.Balls.class, configuration);
    }

    @Override
    public Long getId(com.okeicalm.simpleJournalEntry.tables.pojos.Balls object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Balls.BALLS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchById(Long... values) {
        return fetch(Balls.BALLS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.okeicalm.simpleJournalEntry.tables.pojos.Balls fetchOneById(Long value) {
        return fetchOne(Balls.BALLS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Balls.BALLS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchByName(String... values) {
        return fetch(Balls.BALLS.NAME, values);
    }

    /**
     * Fetch records that have <code>size BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchRangeOfSize(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Balls.BALLS.SIZE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>size IN (values)</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchBySize(Integer... values) {
        return fetch(Balls.BALLS.SIZE, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchRangeOfPrice(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Balls.BALLS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.okeicalm.simpleJournalEntry.tables.pojos.Balls> fetchByPrice(Integer... values) {
        return fetch(Balls.BALLS.PRICE, values);
    }
}
