/*
 * This file is generated by jOOQ.
 */
package com.okeicalm.simpleJournalEntry.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Balls implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long    id;
    private final String  name;
    private final Integer size;
    private final Integer price;

    public Balls(Balls value) {
        this.id = value.id;
        this.name = value.name;
        this.size = value.size;
        this.price = value.price;
    }

    public Balls(
        Long    id,
        String  name,
        Integer size,
        Integer price
    ) {
        this.id = id;
        this.name = name;
        this.size = size;
        this.price = price;
    }

    /**
     * Getter for <code>simple_journal_entry_db.balls.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>simple_journal_entry_db.balls.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>simple_journal_entry_db.balls.size</code>.
     */
    public Integer getSize() {
        return this.size;
    }

    /**
     * Getter for <code>simple_journal_entry_db.balls.price</code>.
     */
    public Integer getPrice() {
        return this.price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Balls (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(size);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
